[versions]
junit = "5.14.4"
spigot = "1.12.2-R0.1-20180712.012057-156"
snakeyaml = "1.33"
adventure = "4.17.0"
item-nbt-api = "2.12.4"
placeholderapi = "2.11.6"
sqlite-jdbc = "3.45.3.0"
mysql-connector = "8.4.0"
h2 = "1.4.200"
gson = "2.10.1"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
spigot-api = { module = "org.spigotmc:spigot-api", version.ref = "spigot" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
adventure-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
item-nbt-api = { module = "de.tr7zw:item-nbt-api", version.ref = "item-nbt-api" }
placeholderapi = { module = "me.clip:placeholderapi", version.ref = "placeholderapi" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite-jdbc" }
mysql-connector = { module = "com.mysql:mysql-connector-j", version.ref = "mysql-connector" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
